### ISSUE TITLE
java.lang.IllegalArgumentException: URI has a path component

### ISSUE THREAD

**Issue by TX256** [robtimus/ftp-fs#4]
Hi. I'm quite new to FTP in general, so I might be missing something obvious here!

I'm just trying out your library, and attempting to connect to `ftp://speedtest.tele2.net/`, which is a public ftp "test server". But I get an exception:

```
java.lang.IllegalArgumentException: URI has a path component: ftp://speedtest.tele2.net/
	at com.github.robtimus.filesystems.Messages$URIMessages.hasPath(Messages.java:714)
	at com.github.robtimus.filesystems.ftp.FTPFileSystemProvider.checkURI(FTPFileSystemProvider.java:168)
	at com.github.robtimus.filesystems.ftp.FTPFileSystemProvider.newFileSystem(FTPFileSystemProvider.java:89)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:344)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:293)
```

How would I go on resolving this?

**Comment by TX256** [comment]
OK, it was simply caused by the trailing `/`
